apiVersion: apps/v1
kind: Deployment
metadata:
    name: project-4
    labels:
       env: prod
       app: app-4
spec:
   replicas: 2
   selector:
       matchLabels:
           env: prod
           app: app-4
   template:
       metadata:
           labels:
              env: prod
              app: app-4
       spec:
          containers:
              - name: maven
                image: purushothamareddy/myapp:1.4
                ports:
                  - containerPort: 8082
                  
                  
 
---
apiVersion: v1
kind: Service
metadata:
     name: project-4
     labels:
         env: prod
         app: app-4
spec:
  selector:
      app: app-4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer    
